### PR TITLE
Dipoles and Plane wave

### PR DESCRIPTION
**Pull request by sgkang**
- [ ] Finish magnetic dipole
- [ ] Some updates on widgets 
- [ ] Plane wave widget

### CODE REVIEW

**Comment by sgkang** [comment]
image

Any idea @lheagy ?

**Comment by lheagy** [comment]
yes, you need to remove the `@dev/` from the travis.yml file. The way we are installing is not the most transparent, but we are using dev on travis. If you use the travis file on master it should run properly (maybe :) ) 

image

**Comment by lheagy** [comment]
If you didn't edit the travis file, you might want to try restarting the build 

image

**Comment by lheagy** [comment]
It looks like this branch is quite out-of-date with master. I would suggest merging in master first

**Comment by sgkang** [comment]
got it.

2016-08-12 10:35 GMT-07:00 Lindsey Heagy notifications@github.com:

**Comment by lheagy** [comment]
@sgkang : could you take a first pass at resolving the merge conflicts here? Let me know if you run into issues, I can try to help out!

**Pull request closed without merging**
